<div class="part-header">Управление</div>

<div class="item row">
    <div class="label-4"></div>
    <div class="col row">
        <q-checkbox size="xs" v-model="clickControl" label="Включить управление кликом" />
    </div>
</div>

<!--            
            <el-tab-pane label="Управление">
                <el-form :model="form" size="mini" label-width="120px" @submit.native.prevent>
                    <div class="partHeader">Управление</div>

                    <el-form-item label="">
                        <el-checkbox v-model="clickControl">Включить управление кликом</el-checkbox>
                    </el-form-item>
                </el-form>
            </el-tab-pane>
-->